name: cbc
version: 0.1.0.0
github: githubuser/cbc
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2018 Author name here
extra-source-files:
  - README.md
  - ChangeLog.md
description: 'Please see the README on Github at <https://github.com/githubuser/cbc#readme>'
dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - fgl
  - mtl
  - transformers
  - megaparsec
  - filepath
  - containers
  - pretty
  - GenericPretty
  - split
  - directory
library:
  source-dirs: src
executables:
  cbc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - cbc
tests:
  cbc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - cbc
