library:
  source-dirs: src
tests:
  cbc-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cbc
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- vector
- base >= 4.7 && < 5
- bytestring
- fgl
- mtl
- transformers
- megaparsec
- filepath
- containers
- pretty
- GenericPretty
- split
- directory
name: cbc
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/cbc
license: BSD3
executables:
  cbc-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cbc
description: Please see the README on Github at <https://github.com/githubuser/cbc#readme>
